services:
  subscription-reminder:
    image: ghcr.io/maomao63/subscription-reminder:latest
    pull_policy: always
    container_name: subscription-reminder
    restart: unless-stopped
    ports:
      - "13000:13000"
    volumes:
      - "${CONFIG_PATH:-./config}:/config"
    environment:
      TZ: "${TZ:-Europe/Berlin}"
      PUID: "${PUID:-99}"
      PGID: "${PGID:-100}"
